# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 17:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R', models.FloatField(default=1.0, verbose_name=b' resistencia (ohm)')),
                ('L', models.FloatField(default=0.5, verbose_name=b' inductancia (H)')),
                ('Km', models.FloatField(default=0.01, verbose_name=b' ctte fuerza electromotriz = ctte torque')),
                ('b', models.FloatField(default=0.1, verbose_name=b' coeficiente de friccion (Nms)')),
                ('J', models.FloatField(default=0.01, verbose_name=b' inercia (Kgm^2)')),
                ('P', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[-1, -2, -3], size=None, verbose_name=b' Polos')),
            ],
        ),
    ]
